# permissions for end users to view multiclusterobservabilities.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: multiclusterobservability-viewer-role
rules:
- apiGroups:
  - observability.open-cluster-management.io
  resources:
  - multiclusterobservabilities
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - observability.open-cluster-management.io
  resources:
  - multiclusterobservabilities/status
  verbs:
  - get
