# permissions for end users to view observabilityaddons.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: observabilityaddon-viewer-role
rules:
- apiGroups:
  - observability.open-cluster-management.io
  resources:
  - observabilityaddons
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - observability.open-cluster-management.io
  resources:
  - observabilityaddons/status
  verbs:
  - get
