apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: mco.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: MultiClusterObservability is the Schema for the multiclusterobservabilities API
      displayName: Multi Cluster Observability
      kind: MultiClusterObservability
      name: multiclusterobservabilities.observability.open-cluster-management.io
      version: v1beta1
    - description: ObservabilityAddon is the Schema for the observabilityaddons API
      displayName: Observability Addon
      kind: ObservabilityAddon
      name: observabilityaddons.observability.open-cluster-management.io
      version: v1beta1
  description: The multicluster-observability-operator is a component of ACM observability feature. It is designed to install into Hub Cluster.
  displayName: Multicluster Observability Operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - MultiClusterObservability
  links:
  - name: Mco
    url: https://mco.domain
  maintainers:
  - email: acm-contact@redhat.com
    name: acm-contact
  maturity: alpha
  provider:
    name: Red Hat, Inc
  version: 0.0.0
